spring:
  application:
    name: spring-boot-carnet
  # OracleDB connection settings
  # datasource:
  #   url: jdbc:oracle:thin:@localhost:1521/xe
  #   username: C##MASOOD
  #   password: --------
  #   driver-class-name: oracle.jdbc.OracleDriver

  # used for h2 to tell to create schema each time
  # sql:
  #   init:
  #     mode: always


# Custom connection settings
custom:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: C##MASOOD
    password: "******"
    driver-class-name: oracle.jdbc.OracleDriver


